/* ══════════ MANAGER VOYAGE · MANAGER FOUNDATIONS · course 1 · narration ══════════
   One script per page, keyed by the pager's <section>/<n>. Eighteen pages. The Listen
   button plays assets/audio/foundation/<key>-<n>.mp3 (recorded from these
   exact words) and falls back to the browser's speech synthesis. Plain
   language: where you are, why this matters, what to do on this page,
   what is next. Yukl's research is the guide behind the four jobs, not
   the vocabulary in front of them. MV_VIDEO_NARR is muxed into the
   training videos by scripts/build-media.py, which also writes captions.
   No em or en dashes. */
window.MV_NARR = {
  'home/1': 'Welcome to the first course in Manager Foundations. You are a manager now, and this course starts at the beginning. Here is where it fits. Manager Foundations is the part of Manager Voyage that sets the stage: what every manager here needs to know. You should already have started, or finished, your manager compliance courses. After this course, the micro modules teach the common manager tasks, one at a time. Here is what you will get, in about twenty minutes: what changed when you became a manager; what a manager is and is not; five ideas the best-known voices on management agree on; what Vanderbilt will ask you to do this year, and who helps; and one simple picture to keep the whole job in view. Turn pages with the arrows at the bottom right. Use Listen on any page, or turn on Auto to hear every page. Next: a short overview.',
  'overview/1': 'The course overview. Five modules. Module one: what changed, and what a manager is. Module two: five ideas that hold up, from Stephen Covey, Brené Brown, Amy Edmondson, Simon Sinek, and SHRM, and a page on making it safe to speak up. Module three: what Vanderbilt will ask you to do this year, when, and who helps, then five situations to decide: handle it, ask PCB, route it, or report it. Module four: the four jobs of a manager, one picture that holds the whole job, with a short video for each and four situations for your call. Module five: the survey you already took, and a self-rating that sets the order of your micro modules. Then a five-question check and your next seven days. Eight sections track your progress as you go. Read the module cards, then turn the page.',
  'shift/1': 'Module one: what changed. Here is the one change that makes you a manager. Before, your job was your work, and you were measured on what you produced. Now your job is the team’s work, and the people who do it. Three things are new. One, you decide: what matters this week, who does what, and what waits. Two, you approve: timecards, time off, expenses, and requests come to you, and Vanderbilt trusts your signature. Three, you are responsible for people: fair treatment, a safe place to speak up, a chance to grow, and the right help when life happens. And three things a manager is not: not the person who does everyone’s work, not a friend first, and not the police; some things you send on, the same day. On this page, sort six things that happen in a normal month: is it your job now, your team member’s, or another office’s? All six sorted marks the section done. Next: what a manager is.',
  'basics/1': 'What a manager is. Here is the definition, in one sentence: a manager is the person responsible for a team’s work, and for the people who do it. Three questions every manager answers every week. Does everyone know what to do this week? Is anyone stuck, struggling, or waiting on me? What is coming that the team should hear from me first? You do not have to know everything on day one. You do have to know who helps. Your unit leader is the leader your team reports up to. People, Culture and Belonging, or PCB, is Vanderbilt’s HR. Your PCB partner is the person assigned to your unit, your first call for anything about people. Your Engagement Consultant supports managers in your business unit. The leave office handles time off for health and family. Equal Opportunity and Access, or EOA, handles discrimination and harassment reports. And your dashboard, My Voyage, has the micro modules and who to call. Watch the eighty-second video, then turn the page for five ideas that hold up.',
  'ideas/1': 'Module two: five ideas the best-known voices on management agree on, one at a time. One, Stephen Covey: put first things first. Picture a jar. Fill it with sand, the email and the small requests, and the big rocks never fit; put the big rocks in first and the sand settles around them. Your big rocks are the three things that matter this week. Two, Brené Brown: clear is kind, unclear is unkind. Hinting feels polite and leaves people guessing for weeks. Say the expectation, the deadline, and the feedback plainly and early, in private. Three, Amy Edmondson: people only speak up when it is safe to. She found that the best teams report more mistakes, not fewer, because they feel safe enough to say so and fix them early. Your reaction the first time someone brings bad news decides whether there is a second time. Four, Simon Sinek: start with why, and leaders eat last. Say the why before the what, and when it is tight, put the team’s needs before your own comfort. Five, SHRM, the Society for Human Resource Management: the people work is the manager’s work. Hiring, onboarding, expectations, feedback, leave, and hard conversations are yours; PCB, People, Culture and Belonging, shows you how. Read each idea, note the one thing to start this week, and pick the one you will try first. Next: three moments that build trust or break it.',
  'safe/1': 'Safe to speak up. Here is the idea in plain words: people will tell you the truth, ask questions, and try things only if it is safe to. Amy Edmondson calls it psychological safety, and her research is clear: teams that speak up catch problems earlier and learn faster. Three moments decide it. Someone brings you bad news. Someone asks a question in front of the team. Someone makes a mistake. On this page, each moment gives you three responses. Tap the one you would actually say, and read what happens next. The rule, in one line: thank first, solve second, learn the cause later, and never in front of the team. Find the response that keeps people talking in all three moments; that marks the section done. Next: what Vanderbilt will ask you to do this year.',
  'year/1': 'Module three: what Vanderbilt will ask you to do, and when. Nothing on this page should surprise you when it lands, because each task has a short how-to, a micro module, on your dashboard. Four groups. Every week: a short one-on-one with each person, a look at work before it is due, timecards and time off to approve, and questions to answer or pass on. Every month or quarter: expenses, goals in Culture Amp, feedback, and thanks. A few times a year: performance reviews, the compensation cycle, hiring when a seat opens, onboarding a new hire, and someone leaving. And when it happens: a leave request, a flexible work request, an accommodation request, a concern about a coworker, a performance concern, and anything you must report. Tap each group to open it, and note the micro module named in brackets. All four open, then turn the page to make your first calls.',
  'calls/1': 'Your first calls. Most manager moments come down to one question: do I handle this myself, ask my PCB partner first, send it to the leave office, or report it to EOA? Handle it when it is a normal manager task: time off, a timecard question, a one-on-one, feedback. Ask your PCB partner first when there is a process: pay, hiring, a performance concern, discipline, or anything you are unsure of. The leave office, the same day, for anything that sounds like time off for health or family; you never ask for a diagnosis. EOA, the same day, for anything that sounds like discrimination, harassment, or misconduct; you report it, you do not investigate it. Five situations on this page. Tap the first thing you would do, read the feedback, and move on. All five decided marks the section done. Next: module four, the four jobs.',
  'welcome/1': 'Module four: the four jobs of a manager. You now know what a manager is and what Vanderbilt will ask of you. This module gives you one simple picture to hold it all: four jobs. Job one: get the work done. Job two: take care of your people. Job three: make things better. Job four: connect your team to the rest of Vanderbilt. Nothing new to memorize; it is the same work, sorted, and the survey you took before this course asks about the same habits. Watch the ninety-second video, then tap each of the four cards to see the habits inside. When all four are open, this section marks itself done. The next four pages take one job each.',
  'task/1': 'Job one: get the work done. Here is why it matters. When people are not sure what is expected, work comes in late, gets redone, or quietly drops, and you find out on the due date. Four habits fix that: plan it, say it, check it, and fix it. Watch the video to see each one on a normal Tuesday. Then flip each card: the front is the habit, the back is what to stop doing and what to do instead. Your one thing for this week is in the gold box. Next: job two, take care of your people.',
  'relations/1': 'Job two: take care of your people. Here is why it matters. People stay, and do their best work, for a manager who notices them. Four habits: listen and help, grow them, thank them, and trust them with real decisions. Two things to notice in the video. Being friendly is not the same as helping. And there is a line: when someone mentions leave, a health issue, or unfair treatment, part of your job is to send it to the right office the same day, the way you practiced two pages ago. Watch, flip the cards, and take the one thing for this week. Next: job three, make things better.',
  'change/1': 'Job three: make things better. Here is why it matters. Vanderbilt is asking every team to move faster and improve, and that does not happen from the top. It happens in your team, in small ways, every week. Four habits: explain the why, describe where the team is going, let people try new ideas, and look back after big work. None of them is a reorganization, and the first one is Simon Sinek’s idea from module two. Watch the video, flip the cards, and take the one thing for this week. Next: job four, connect your team.',
  'external/1': 'Job four: connect your team to the rest of Vanderbilt. Here is why it matters. Your team needs things it does not control: approvals, information, help from other offices, and a fair hearing when someone asks too much of you. Most new managers do not know this is part of the job, so it is the one they do least. Three habits: know the people your team depends on before you need them, watch for what is coming, and speak up for your team with facts. Watch the video, flip the cards, and take the one thing for this week. Next: your call, four situations, one for each job.',
  'yourcall/1': 'Your call: four situations, one for each job. A report due Friday that nobody has mentioned. A team member whose dad is in the hospital. A new system the team already hates. A request from another office that would break your month. In each one, tap the response you would actually give, read what happens next, then try the other two; the consequences teach more than the right answer does. Finding the Vanderbilt way in all four marks the section done. Next: module five, the survey, and where you stand.',
  'survey/1': 'Module six: the survey, and your self-rating. Before this course you completed a short survey, the Managerial Practices Survey. It asked how often you do each of fifteen habits. Those are the habits you just learned, so you can now read your results with the names attached. Nobody passes or fails it, and your Engagement Consultant can walk through your results with you. Six months after you finish this course, you take it again, so the change shows. Here is what to do now. Rate yourself on each habit, one at a time: rarely, sometimes, or often, thinking of a normal month. Be honest; a low score just means a habit to build. You will get a first picture of where you stand, the three habits to work on first, and your micro modules in that order.',
  'quiz/1': 'A quick check. Five questions, one at a time, with the answer explained after each. Four right finishes the course, and you can retake it anytime. Go.',
  'nextstep/1': 'What you now know, and your next seven days. The recap: a manager has four jobs. Get the work done. Take care of your people. Make things better. Connect your team. Now three moves. One: open your dashboard today; your micro modules are there in your order, and so is who to call. Two: this week, do the one habit your self-rating pointed to, once, on purpose. Three: in six months, take the survey again and see what changed. Then copy the message on this page and send it to your unit leader.',
  'end/1': 'That is the course. Four jobs, one habit to try this week, and a dashboard that now knows where to start you. Take your first micro module today, and when the survey comes back around in six months, answer it honestly. Open My Voyage.'
};

/* Narration muxed into each training video, with captions built from it.
   Shape: the job in one line, why it matters, each habit on a Tuesday,
   what to stop doing, one thing to do this week, and the cue. */
window.MV_VIDEO_NARR = {
  'basics': 'What a manager is. You are a manager now, and here is what that means, in plain words. Before, your job was your own work. Now your job is your team’s work, and the people who do it. That is the whole change, and it is a big one. Three things are new. One: you decide. What matters this week, who does what, and what waits. If you do not decide, the loudest request decides for you. Two: you approve. Timecards, time off, expenses, and requests now come to you, and Vanderbilt trusts your signature, so look before you sign. Three: you are responsible for people. Fair treatment, a safe place to speak up, a chance to grow, and the right help when life happens. You do not have to know everything. You have a PCB partner, an Engagement Consultant, a leave office, and a micro module for every common task. What you do have to do is show up as the manager: decide, approve, and take care of the people. And one thing a manager is not: the person who does everyone’s work. When you are tempted to just do it yourself, that is the moment to manage instead. Next: five ideas the best-known voices on management agree on.',
  'framework': 'The four jobs of a manager. Here is the idea in one sentence: being a manager is not a title, it is four jobs you do every week. Job one: get the work done. Decide what matters, tell people what is expected, check work before it is due, and fix problems at the cause. Job two: take care of your people. Listen and help, grow them, thank them for specific work, and trust them with real decisions. Job three: make things better. Explain the why behind changes, describe where the team is going, let people try new ideas, and look back after big work. Job four: connect your team to the rest of Vanderbilt. Know the people your team depends on, watch for what is coming, and speak up for your team with facts. Every manager does all four. Most weeks need one of them more than the others, and part of the job is noticing which. These four jobs come from research by Gary Yukl. Vanderbilt uses them as a guide, and the survey you took before this course asks about the same habits. Now tap each card on the page to see the habits inside each job.',
  'task': 'Job one: get the work done. Why it matters: when people are not sure what is expected, work comes in late, gets redone, or quietly drops, and you find out on the due date. Four habits fix that. Plan it: before the quarter starts, pick three priorities, give each one an owner, and decide what moves if a new request lands. Say it: every person can tell you, without notes, what they own, by when, and what good looks like, and it is written where they can see it, not kept in your head. Check it: look at the work while it is in progress, in your weekly one-on-one, not the finished product on the due date. Fix it: when something breaks twice, find the cause and change something, instead of fixing it a third time yourself. What to stop doing: assuming the team knows, sending the goal in one email, checking only when it is late, and doing the work yourself because it is faster. This week: pick one person and confirm, out loud, what they own and by when. Now flip the four cards on the page; the back of each shows what to stop doing and what to do instead.',
  'relations': 'Job two: take care of your people. Why it matters: people stay, and do their best work, for a manager who notices them. This is where your team’s engagement is made or lost. Four habits. Listen and help: someone mentions a hard week at home; you listen, move what you can, and check in on Monday. And know the line: if they mention leave, a health issue, or unfair treatment, send it to the right office the same day, and never ask for a diagnosis. Grow them: once a quarter, without a form, ask what each person wants to be doing in two years, and find one assignment that stretches toward it. Thank them: the way you handled the vendor call on Thursday kept us on schedule, said on Friday. Specific, by name, that week. Great job everyone thanks nobody. Trust them: hand over the decision, not just the task, and ask the team before you set a new process. What to stop doing: being friendly instead of helpful, and saving growth for the annual review. This week: thank one person for one specific thing. Now flip the cards, then turn the page.',
  'change': 'Job three: make things better. Why it matters: Vanderbilt is asking every team to move faster and improve, and that does not happen from the top. It happens in your team, in small ways, every week. Four habits, and none of them is a reorganization. Explain the why: a new system is coming from central; tell your team the reason in your own words at Thursday’s meeting, before Tuesday’s campus email, and write down their objections to take back. Describe where you are going: in two sentences, what your team will be able to do next year that it cannot do now. Let people try: someone suggests a new way to run the weekly report; say, try it for two weeks and show me. Look back: ten minutes after any big piece of work, what worked, what did not, what changes, written where the next person can find it. What to stop doing: forwarding the announcement, and saying that is not how we do it here. This week: hold one ten-minute look-back. Now flip the cards on the page; your call on the new system comes after job four.',
  'external': 'Job four: connect your team to the rest of Vanderbilt. Why it matters: your team needs things it does not control: approvals, information, help from other offices, and a fair hearing when someone asks too much of you. Most new managers do not know this is part of the job, so it is the one they do least. Three habits. Know the people: your PCB partner, your Engagement Consultant, the person in Finance who approves your requests, and a peer manager in another unit, by name, before you need any of them. Watch for what is coming: read the compensation calendar in August and tell your team in September what October will bring, instead of hearing it from them. Speak up for your team: when another office’s request would break your month, show the hours, name the conflict, offer two options, and negotiate the date, instead of absorbing it or refusing it. What to stop doing: meeting your PCB partner at the first crisis. This week: have coffee with one person your team depends on. Now flip the three cards on the page; your call on that request comes next.'
};
