/* ══════════ MANAGER VOYAGE · MANAGER FOUNDATIONS · course 1 · narration ══════════
   One script per page, keyed by the pager's <section>/<n>, plus one short clip per
   tab, moment, situation, or card (ideas/t1, safe/m1, yourcall/s1, year/g1, welcome/j1). The Listen
   button plays assets/audio/foundation/<key>-<n>.mp3 (recorded from these
   exact words) and falls back to the browser's speech synthesis. Plain
   language: where you are, why this matters, what to do on this page,
   what is next. Yukl's research is the guide behind the four jobs, not
   the vocabulary in front of them. MV_VIDEO_NARR is muxed into the
   training videos by scripts/build-media.py, which also writes captions.
   No em or en dashes. */
window.MV_NARR = {
  'home/1': 'Welcome to the first course in Manager Foundations. You are a manager now, and this course starts at the beginning. Take your manager compliance courses first. The micro modules come after. In about twenty minutes: what changed when you became a manager, what a manager is, five ideas that hold up, what Vanderbilt will ask of you this year, and one picture to keep it all in view. Turn pages with the arrows at the bottom right. Tap Listen on any page, or turn on Auto to hear every page. Where a page has tabs or cards, each one has its own short clip, so the audio goes at your pace. Next: a short overview.',
  'overview/1': 'The course overview. Five topics. One: what changed, and what a manager is. Two: five ideas every good manager relies on, then five moments to practice them. Three: what Vanderbilt will ask you to do this year, and your first calls: handle it, ask, route, or report. Four: the four jobs of a manager, one page each. Five: your Manager Effectiveness Assessment results, and your starting point. Then a quick check, your next seven days, and a keep-learning list. Eight activities track your progress. Turn the page.',
  'shift/1': 'Topic one: what changed. Your job used to be your work. Now it is the team’s work, and the people who do it. Three things are new. You decide: what matters this week, who does what, what waits. You approve: timecards, time off, expenses. Look before you sign. You are responsible for people: fair treatment, a safe place to speak up, a chance to grow. And three things a manager is not. Not the person who does everyone’s work. Not a friend first. Not the police; some things you send on, the same day. Now sort six things from a normal month: yours, your team member’s, or another office’s. Next: what a manager is.',
  'basics/1': 'What a manager is, in one sentence: the person responsible for a team’s work, and for the people who do it. Three questions, every week. Does everyone know what to do this week? Is anyone stuck, struggling, or waiting on me? What is coming that the team should hear from me first? You do not have to know everything on day one. You do have to know who helps. Your unit leader, for direction. Your Engagement Consultant, your HR business partner, for the bigger people questions. Your HCM, in most business units, for immediate HR issues. The leave office and EOA, the same day. And My Voyage, your dashboard. Watch the short video, then turn the page for five ideas that hold up.',
  'ideas/1': 'Topic two: five ideas every good manager relies on. Setting priorities. Clear expectations. Psychological safety. Purpose. And the people work. Each tab gives you three things: what the idea is, how you use it as a manager, and the value it brings, plus one thing to start this week. Tap a tab to hear that idea on its own. Read all five, and note the one you will try first. Next: each idea in the moment it comes up.',
  'safe/1': 'The ideas at work. Five moments, one per idea. A Monday inbox. A summary that came back twice. Bad news. A change to hand out. Work that slipped. In each one, tap the response you would actually give and read what happens next. Then try the other two; the consequences teach more than the right answer. Each moment has its own clip. Finding the best response in all five completes the activity. Next: topic three, your first year.',
  'year/1': 'Topic three: what Vanderbilt will ask you to do, and when. Four groups. Every week. Every month or quarter. A few times a year. And when it happens. Tap each group to open it and hear it. Each task names its micro module in brackets, so nothing on this page should surprise you when it lands. All four open, then turn the page to make your first calls.',
  'calls/1': 'Your first calls. Most manager moments come down to one question: do I handle this myself, ask my HCM first, send it to the leave office, or report it to EOA? Handle a normal manager task. Ask your HCM when there is a process, or when you are unsure. The leave office, the same day, for health or family time off; never ask for a diagnosis. EOA, the same day, for discrimination, harassment, or misconduct; you report it, you do not investigate it. Two tools here. The situation simulator: pick anything from a leave request to a resignation and see the first move. Then five situations to decide. All five decided completes the activity. Next: topic four, the four jobs.',
  'welcome/1': 'Topic four: the four jobs of a manager. One picture that holds the whole job. Get the work done. Take care of your people. Make things better. Connect your team to the rest of Vanderbilt. Nothing new to memorize; it is the same work, sorted, and the assessment you took before this course scores the same habits. Watch the short video, then tap each card to open it and hear the habits inside. All four open completes the activity. The next four pages take one job each.',
  'task/1': 'Job one: get the work done. Four habits. Plan it: the steps, the people, the dates, before the work starts. Say it: what good looks like, out loud and in writing. Check it: look at the work before it is due, not after. Fix it: find the cause when something breaks, not the person. The habit to stop: doing the work yourself. Watch the video, flip the four cards, and take the one thing for this week. Next: job two.',
  'relations/1': 'Job two: take care of your people. Four habits. Listen and help: ask about the load before they raise it. Grow them: feedback they can act on, and work that stretches. Thank them: for specific work, soon after. Trust them: hand over the decision, not just the task. The one thing to route: anything that sounds like leave, to the leave office, the same day. Watch the video, flip the cards, take one thing for this week. Next: job three.',
  'change/1': 'Job three: make things better. Vanderbilt is asking every team to move faster and improve, and that happens in your team, in small ways, every week. Four habits. Explain the why. Describe where the team is going. Let people try. Look back after big work. None of them is a reorganization, and the first is the purpose idea from topic two. Watch the video, flip the cards, take one thing for this week. Next: job four.',
  'external/1': 'Job four: connect your team to the rest of Vanderbilt. Your team needs things it cannot get alone: information, decisions, help from other offices. Three habits. Know the people your team depends on. Watch for what is coming, so the team hears it from you first. Speak up for your team, with facts and options, before you say yes to the weekend. Watch the video, flip the cards, take one thing for this week. Next: your call.',
  'yourcall/1': 'Your call: four situations, one for each job. A report due Friday that nobody has mentioned. A team member whose dad is in the hospital. A new system the team already hates. A request from another office that would break your month. Tap the response you would actually give, read what happens, then try the other two. Each situation has its own clip. The Vanderbilt way in all four completes the activity. Next: topic five, your results.',
  'survey/1': 'Topic five: your results. Before this course you completed the Manager Effectiveness Assessment: fourteen questions on how often you do the habits you just learned. Your results come by email as a score out of seventy and one of three bands. Developing, under thirty-five: start with jobs one and two. Strong, thirty-five to fifty-five: start with your lowest job. Advanced, fifty-six and above: the step up is jobs three and four. Nobody passes or fails. Tap each job to see which questions it covers. Then enter your band and lowest job, and you get your starting point. Six months after you finish, you take it again.',
  'quiz/1': 'A quick check. Five questions, one at a time. Four of five finishes the course, and you can retake it anytime. Each answer tells you why. Next: your next seven days.',
  'nextstep/1': 'Your next seven days. The recap: four jobs. Get the work done. Take care of your people. Make things better. Connect your team. Three moves. Today: open your dashboard; your micro modules are there in your order. This week: practice the one habit your results pointed to, once, on purpose. In six months: take the assessment again. Then copy the message on this page and send it to your unit leader. Next: keep learning.',
  'learn/1': 'Keep learning. A short, chosen list, not the whole catalog: courses in Oracle Learning, a few podcasts, a few videos, by topic. Each one says why it is on the list. The micro modules on your dashboard come first. Then pick one item from this page a month, on the job your results pointed to. Next: the wrap-up.',
  'end/1': 'That is the course. Four jobs, one habit to try this week, and a dashboard that knows where to start you. Take your first micro module today, and when the assessment comes back around in six months, answer it honestly. Open My Voyage.',
  'ideas/t1': 'Setting priorities: the big rocks method. Picture a jar. Sand first, the email and the small requests, and the big rocks never fit. Big rocks first, and the sand settles around them. As a manager: Monday, before email, name this week’s three big rocks for the team, put them on the calendar, and tell the team so they can protect them too. The value: your calendar will fill itself, and the urgent is rarely the important. A team that knows this week’s three things wastes less and finishes more. Start this week: write your three big rocks before you open your inbox.',
  'ideas/t2': 'Clear expectations and feedback: clear is kind, unclear is unkind. Softening expectations and delaying feedback feels nice. It does the opposite: people spend weeks guessing what you meant, and the problem grows. As a manager: say what you expect, by when, and what good looks like, out loud and in writing. Give feedback close to the moment, in private, with the specific thing you noticed. The value: fewer surprises at the deadline, and a team that always knows where it stands. Start this week: say one thing you have been hinting at. Privately, plainly, kindly.',
  'ideas/t3': 'Psychological safety: people only speak up when it is safe to. It is a team’s shared belief that nobody is punished or embarrassed for a question, a mistake, or a disagreement. The best teams report more mistakes, not fewer, because they catch them early. It is not about being nice; it is about making the truth cheap to tell. As a manager, three moments decide it: bad news, a question in front of others, a mistake. Thank first, solve second, learn the cause later, never in front of the team. The value: you hear about problems while they are small. Start this week: when someone reports a problem, thank them first.',
  'ideas/t4': 'Purpose: start with why, and put the team first. People do their best work when they know why it matters, not just what to do. And a team that feels looked after protects the work and each other. As a manager: before a task or a change, say the why. What it is for, who it helps, what happens if it slips. When credit comes, pass it down. When blame comes, take it first. The value: people who know the why make good decisions when you are not in the room. Start this week: explain the why behind one thing you have been asking for.',
  'ideas/t5': 'The people work: a manager’s core responsibilities. The professional standard for people managers is consistent on one point: hiring, onboarding, expectations, feedback, performance, time and leave, and hard conversations are the manager’s job, not PCB’s. As a manager: you run the one-on-one, give the feedback, start the leave request the same day, open the requisition. Your HCM is your first call when you are unsure; your Engagement Consultant, for the bigger questions. The value: nothing waits for someone else to act. Start this week: find out your HCM’s and your Engagement Consultant’s names.',
  'safe/m1': 'Moment one, priorities. Monday, five past eight. Forty-one emails, two marked urgent, and a one-on-one with Sam at nine. The grant report your team owns is due Thursday and nobody has started it. What do you do first?',
  'safe/m2': 'Moment two, clear expectations. Priya’s summary has come back twice. Both times you wrote, looks good, maybe tighten it up a bit. It is due tomorrow and it is still not what you need. What do you say?',
  'safe/m3': 'Moment three, psychological safety. Jordan tells you on Tuesday that the vendor missed its deadline and the launch will slip a week. She looks braced for your reaction. What is your first sentence?',
  'safe/m4': 'Moment four, purpose. Central is replacing the intake form. You have to tell the team Friday. Two people have already said, here we go again, in the hallway. How do you hand it out?',
  'safe/m5': 'Moment five, the people work. Dev has missed two deadlines this month. A coworker mentions it in passing. You are new, and you would rather PCB handled it. What do you do?',
  'yourcall/s1': 'Situation one, get the work done. It is Wednesday. The monthly report your team owns is due Friday. Priya, who builds it, has not mentioned it in two weeks, and you have not asked. A director just emailed asking whether it will be on time. What do you do?',
  'yourcall/s2': 'Situation two, take care of your people. Marcus, one of your strongest people, stays after the one-on-one and says his dad has been in and out of the hospital. He might need some time off, he is not sure yet, and he did not want you to think he was slacking. What do you say?',
  'yourcall/s3': 'Situation three, make things better. Central is replacing the travel reimbursement system in six weeks. The announcement goes out next Tuesday. Your team already hates the idea. What do you do before the email lands?',
  'yourcall/s4': 'Situation four, connect your team. A director in another unit emails Monday: we need your team to pull a full data reconciliation by Friday for audit prep. Your own month-end close is the same week. Doing both means weekend work. How do you reply?',
  'year/g1': 'Every week: run the team. A short one-on-one with each person. A look at work before it is due. Timecards and time off to approve. Questions to answer, or to find who can. The micro modules: running one-on-ones, setting expectations and goals, time and attendance approvals, and Oracle HCM for managers.',
  'year/g2': 'Every month or quarter: keep it on track. Approve expenses and purchases. Set and check goals in Culture Amp. Give feedback while it is still useful. Thank people for specific work. The micro modules: expense and procurement approvals, Culture Amp, and giving feedback.',
  'year/g3': 'A few times a year: the cycles. Performance reviews. The compensation cycle. Hiring when a seat opens. Onboarding a new hire. Someone leaving. Each has a micro module: Culture Amp, compensation cycle and merit basics, requisitions and hiring, onboarding a new hire, and offboarding and transitions.',
  'year/g4': 'When it happens: know the process, and move the same day. A leave request, including FMLA. A flexible work request. An accommodation request. A concern about a coworker or manager. A performance concern. Something you must report. The micro modules: FMLA and leave, flexible work arrangements, reasonable accommodations, employee relations grounding, performance concerns and progressive discipline, and EOA and reporting obligations.',
  'welcome/j1': 'Job one: get the work done. Is the work getting done, and done well? Four habits. Plan it. Say it. Check it. Fix it.',
  'welcome/j2': 'Job two: take care of your people. Are people growing, and staying? Four habits. Listen and help. Grow them. Thank them. Trust them.',
  'welcome/j3': 'Job three: make things better. Is the team getting better at what it does? Four habits. Explain the why. Describe where you are going. Let people try. Look back.',
  'welcome/j4': 'Job four: connect your team to the rest of Vanderbilt. Does the team get what it needs from outside? Three habits. Know the people. Watch for what is coming. Speak up for your team.'
};

/* Narration muxed into each training video, with captions built from it.
   Shape: the job in one line, why it matters, each habit on a Tuesday,
   what to stop doing, one thing to do this week, and the cue. */
window.MV_VIDEO_NARR = {
  'basics': 'What a manager is. You are a manager now, and here is what that means, in plain words. Before, your job was your own work. Now your job is your team’s work, and the people who do it. That is the whole change, and it is a big one. Three things are new. One: you decide. What matters this week, who does what, and what waits. If you do not decide, the loudest request decides for you. Two: you approve. Timecards, time off, expenses, and requests now come to you, and Vanderbilt trusts your signature, so look before you sign. Three: you are responsible for people. Fair treatment, a safe place to speak up, a chance to grow, and the right help when life happens. You do not have to know everything. You have an HCM, an Engagement Consultant, a leave office, and a micro module for every common task. What you do have to do is show up as the manager: decide, approve, and take care of the people. And one thing a manager is not: the person who does everyone’s work. When you are tempted to just do it yourself, that is the moment to manage instead. Next: five ideas the best-known voices on management agree on.',
  'framework': 'The four jobs of a manager. Here is the idea in one sentence: being a manager is not a title, it is four jobs you do every week. Job one: get the work done. Decide what matters, tell people what is expected, check work before it is due, and fix problems at the cause. Job two: take care of your people. Listen and help, grow them, thank them for specific work, and trust them with real decisions. Job three: make things better. Explain the why behind changes, describe where the team is going, let people try new ideas, and look back after big work. Job four: connect your team to the rest of Vanderbilt. Know the people your team depends on, watch for what is coming, and speak up for your team with facts. Every manager does all four. Most weeks need one of them more than the others, and part of the job is noticing which. These four jobs come from research by Gary Yukl. Vanderbilt uses them as a guide, and the assessment you took before this course scores the same habits. Now tap each card on the page to see the habits inside each job.',
  'task': 'Job one: get the work done. Why it matters: when people are not sure what is expected, work comes in late, gets redone, or quietly drops, and you find out on the due date. Four habits fix that. Plan it: before the quarter starts, pick three priorities, give each one an owner, and decide what moves if a new request lands. Say it: every person can tell you, without notes, what they own, by when, and what good looks like, and it is written where they can see it, not kept in your head. Check it: look at the work while it is in progress, in your weekly one-on-one, not the finished product on the due date. Fix it: when something breaks twice, find the cause and change something, instead of fixing it a third time yourself. What to stop doing: assuming the team knows, sending the goal in one email, checking only when it is late, and doing the work yourself because it is faster. This week: pick one person and confirm, out loud, what they own and by when. Now flip the four cards on the page; the back of each shows what to stop doing and what to do instead.',
  'relations': 'Job two: take care of your people. Why it matters: people stay, and do their best work, for a manager who notices them. This is where your team’s engagement is made or lost. Four habits. Listen and help: someone mentions a hard week at home; you listen, move what you can, and check in on Monday. And know the line: if they mention leave, a health issue, or unfair treatment, send it to the right office the same day, and never ask for a diagnosis. Grow them: once a quarter, without a form, ask what each person wants to be doing in two years, and find one assignment that stretches toward it. Thank them: the way you handled the vendor call on Thursday kept us on schedule, said on Friday. Specific, by name, that week. Great job everyone thanks nobody. Trust them: hand over the decision, not just the task, and ask the team before you set a new process. What to stop doing: being friendly instead of helpful, and saving growth for the annual review. This week: thank one person for one specific thing. Now flip the cards, then turn the page.',
  'change': 'Job three: make things better. Why it matters: Vanderbilt is asking every team to move faster and improve, and that does not happen from the top. It happens in your team, in small ways, every week. Four habits, and none of them is a reorganization. Explain the why: a new system is coming from central; tell your team the reason in your own words at Thursday’s meeting, before Tuesday’s campus email, and write down their objections to take back. Describe where you are going: in two sentences, what your team will be able to do next year that it cannot do now. Let people try: someone suggests a new way to run the weekly report; say, try it for two weeks and show me. Look back: ten minutes after any big piece of work, what worked, what did not, what changes, written where the next person can find it. What to stop doing: forwarding the announcement, and saying that is not how we do it here. This week: hold one ten-minute look-back. Now flip the cards on the page; your call on the new system comes after job four.',
  'external': 'Job four: connect your team to the rest of Vanderbilt. Why it matters: your team needs things it does not control: approvals, information, help from other offices, and a fair hearing when someone asks too much of you. Most new managers do not know this is part of the job, so it is the one they do least. Three habits. Know the people: your HCM, your Engagement Consultant, the person in Finance who approves your requests, and a peer manager in another unit, by name, before you need any of them. Watch for what is coming: read the compensation calendar in August and tell your team in September what October will bring, instead of hearing it from them. Speak up for your team: when another office’s request would break your month, show the hours, name the conflict, offer two options, and negotiate the date, instead of absorbing it or refusing it. What to stop doing: meeting your HCM at the first crisis. This week: have coffee with one person your team depends on. Now flip the three cards on the page; your call on that request comes next.'
};
