/* ══════════ MANAGER VOYAGE · FOUNDATION · narration scripts ══════════
   One script per page, keyed by the pager's <section>/<n>. The Listen button
   plays assets/audio/foundation/<key>-<n>.mp3 when it exists (generated
   from these exact words with Runway) and falls back to the browser's
   speech synthesis otherwise. MV_VIDEO_NARR holds the narration muxed into
   each custom video by scripts/build-media (see .github/media-urls.json).
   No em or en dashes. */
window.MV_NARR = {
  'home/1': 'Welcome to the Manager Voyage foundation: what Vanderbilt expects of a manager. Management is a job with a definition. Most managers never get one; they inherit habits from whoever managed them. In the next thirty minutes you will get the definition every Vanderbilt manager shares, the vocabulary for it, and the measure we use. Turn pages with the arrows below, do each activity as it comes, and each section marks itself done when you finish.',
  'belief/1': 'Here is the belief this program rests on. A manager is the single greatest influence on a team’s engagement. Vanderbilt will not leave what management means to chance.',
  'mission/1': 'Chancellor Diermeier’s vision is one sentence: Vanderbilt will define the great university of the twenty-first century and be it. The how is uncommon speed, agility, and scale. Those are not properties of a strategy. They are properties of how forty-six hundred staff are managed, day to day, by you and your peers. The university delivers on the vision in three ways: exceptional core operations, bold strategic initiatives, and industry leadership.',
  'mission/2': 'Each of those three is a category of management at the scale of one team. Exceptional core operations is task-oriented management done well. Bold initiatives need change-oriented managers. Industry leadership is external behavior. Reputation and resources feed each other in a flywheel that now turns in five cities. And as the Chancellor says, we are scaling Everest, and we will support one another at every step of the way.',
  'how/1': 'The foundation has six segments of about five minutes each. First, what management is. Then one segment for each of the four categories of behavior: task, relations, change, and external. Finally, the Managerial Practices Survey and your own first profile. A short knowledge check closes the course. Eight sections in total, and the progress bar at the top tracks them.',
  'welcome/1': 'Segment one. Why we are defining management. You were promoted or hired because you are good at the work. Management is a different job, and until now Vanderbilt never told anyone what that job was. Every manager filled in the blank with whatever they had seen, so forty-six hundred staff experienced a few hundred different versions of management. This course ends the luck. It gives you the definition, the words, and the survey that measures it.',
  'welcome/2': 'The framework, on one page. Vanderbilt uses Gary Yukl’s taxonomy of leadership behavior: four categories and fifteen behaviors. Each category answers a different question. Task: is the work getting done well? Relations: are the people growing and staying? Change: is the team getting better at what it does? External: is the team connected to what it needs outside itself? Tap each category to open it, and watch the forty-second explainer.',
  'welcome/3': 'Fact or fiction. Six things you will hear about management in any hallway on campus. Tap each claim to see the answer. When all six are revealed, this section marks itself done.',
  'task/1': 'Segment two. Task-oriented behavior: get the work done well. This category is about efficiency and reliability. The work gets done, done right, and done on time. It is the category new managers most often skip, because they assume the team knows what they know. The team does not.',
  'task/2': 'The four task-oriented behaviors. Planning: decide what, who, when, and with what. Clarifying: say what is expected, by when, and how good. Monitoring: check progress and quality before the deadline. Problem solving: find the cause, decide, and act. Flip each card for what it looks like on a Tuesday and where Manager Voyage practices it.',
  'task/3': 'Habit or the Vanderbilt way. Eight statements. Some are the habit a new manager falls into. Some are how Vanderbilt expects it done. Tap each one to sort it.',
  'task/4': 'Your call. One situation, three responses. Pick the one you would actually do, then read what happens next.',
  'task/5': 'Name the behavior. Six things a Vanderbilt manager did this week. Tap the task-oriented behavior each one is, or not managing when it is doing the work instead of managing it. Then, if you have three minutes, watch the video on what Google learned about great managers.',
  'relations/1': 'Segment three. Relations-oriented behavior: build the people. This category builds the trust, skill, and commitment that task behavior runs on. It is where Vanderbilt’s engagement scores are made or lost, and it is the category the cohort spends the most time rehearsing.',
  'relations/2': 'The four relations-oriented behaviors. Supporting: show concern, listen, and help with the load. Developing: coach, mentor, and open the next door. Recognizing: praise good work, specifically and soon. Empowering: delegate real decisions and consult before you decide. Flip each card.',
  'relations/3': 'Habit or the Vanderbilt way. Being friendly is not the same as supporting. Great job everyone is not recognizing. Tap each statement to sort it.',
  'relations/4': 'Your call. A team member tells you something that is half a personal disclosure and half a leave request. Pick the response you would actually give.',
  'relations/5': 'Name the behavior. Six situations. One of them has crossed into a duty you must route to Equal Opportunity and Access. Find it. Then watch Simon Sinek on why good leaders make you feel safe.',
  'change/1': 'Segment four. Change-oriented behavior: make the team better. This is how a team adapts, improves, and learns. The Chancellor’s charge is uncommon speed, agility, and scale, and none of those happen at the university level unless they happen at the team level, one manager at a time. Most of it is small and weekly.',
  'change/2': 'The four change-oriented behaviors. Advocating change: explain why, and build support. Envisioning change: describe where the team is going and why it matters. Encouraging innovation: invite the new idea and let it be tried. Facilitating collective learning: debrief, share what worked, and keep it. Flip each card.',
  'change/3': 'Habit or the Vanderbilt way. Forwarding the announcement is not advocating change. That is not how we do it here is the opposite of encouraging innovation. Sort the eight statements.',
  'change/4': 'Your call. A new system is coming from central and your team is already unhappy about it. Pick the response you would actually give.',
  'change/5': 'Name the behavior. Six situations, one of which belongs to another category. Then watch Amy Edmondson on building a psychologically safe workplace, the condition every change behavior depends on.',
  'external/1': 'Segment five. External behavior: connect the team. Every team depends on information, resources, and goodwill it does not control. Vanderbilt is thirty-nine business units, schools, central offices, and now five cities. The manager is the team’s connection to all of it. This is the category new managers most often do not know exists.',
  'external/2': 'The three external behaviors. Networking: know the people your team will need, before you need them. External monitoring: watch for what is coming. Representing: speak for the team and get it what it needs. Flip each card.',
  'external/3': 'Habit or the Vanderbilt way. Meeting your HR partner at the first crisis is the habit. Knowing them by name in week one is the Vanderbilt way. Sort the statements.',
  'external/4': 'Your call. Another unit asks for something that would break your team’s month. Pick the response you would actually give.',
  'external/5': 'Name the behavior. Six situations, and this drill also tests whether you can tell the four categories apart. Then watch the short Harvard piece on managing your boss, which is external behavior pointed upward.',
  'survey/1': 'Segment six. The Managerial Practices Survey. After this foundation you will receive the survey by email from the Futures Learning Hub. It asks how often you do each of the fifteen behaviors you just learned. It measures behavior, not personality or performance. Nobody passes or fails it. Answer for a typical month, not your best week. You get the results back as a profile, and you take it again later in the program so the change shows.',
  'survey/2': 'Your self-rating. Fifteen behaviors, three answers each: rarely, sometimes, or often. Be honest, not modest. When you finish, you get a first profile, the three behaviors to practice first, and the order your micro modules open in.',
  'quiz/1': 'The knowledge check. Eight questions across the six segments. Six or more correct completes the foundation, and you can retake it anytime. Questions one to four are on this page.',
  'quiz/2': 'Questions five to eight. When all eight are answered, choose check my answers.',
  'quiz/3': 'Your score. Each question you missed points back to the segment worth a second look.',
  'summary/1': 'What you now know. Management is behavior: four categories, fifteen behaviors, one measure. Task gets the work done well. Relations builds the people. Change makes the team better. External connects the team. And the survey is a map, not a verdict.',
  'nextstep/1': 'Your next seven days. Complete the survey when it arrives. Practice one behavior this week, the one your self-rating pointed to. Open your dashboard. Meet your HR partner and Engagement Consultant. Bookmark the Manager Portal. Then send your unit leader the two-line message on this page.',
  'end/1': 'Now manage it the same way. You have the definition, the vocabulary, and the measure every Vanderbilt manager shares. The survey is coming. The micro modules are open. From first day to fully formed leader starts now.'
};

/* Narration muxed into each custom video. Written for the clip length. */
window.MV_VIDEO_NARR = {
  'framework': 'Every manager at Vanderbilt does four kinds of work. Task: getting the work done well, through planning, clarifying, monitoring, and problem solving. Relations: building the people, through supporting, developing, recognizing, and empowering. Change: making the team better, by advocating and envisioning change, encouraging innovation, and learning together. And external: connecting the team to the people, information, and resources it needs. Four categories. Fifteen behaviors. One definition of management, and one survey that measures it.',
  'task': 'Task-oriented behavior. Plan the work, say what is expected, check it before the deadline, and solve the problem at its cause. Get the work done well.',
  'relations': 'Relations-oriented behavior. Listen and support. Coach and develop. Recognize good work by name. Delegate real decisions. Build the people.',
  'change': 'Change-oriented behavior. Explain the why. Picture next year. Let the new idea be tried. Debrief and keep what worked. Make the team better.',
  'external': 'External behavior. Know the people your team will need. Watch for what is coming. Speak for your team, with numbers, early. Connect the team.'
};
