/* ══════════ HIRING IN NEW YORK · narration scripts ══════════
   One clip per page, keyed <section>/<page>. These are the exact words the
   narrator records (scripts/build-tts.py, with ElevenLabs), and the words the
   browser reads aloud when a clip is not available. Change a script here and
   the clip re-records on the next build. No em or en dashes: the voice reads
   punctuation, and the pause comes from the sentence. */
window.MV_NARR = {
  'home/1': 'Welcome to Hiring in New York, a ten minute module for anyone at Vanderbilt who hires for a role based in New York. Here is what we will cover. Why New York\'s hiring rules exist. The sequence of a New York hire: two background check phases, with a conditional offer between them. The exact words of that conditional offer. Salary history, and what you may ask instead. How to run a fair, structured interview. Then three real situations for you to decide, and a five question check. The big idea is simple. In New York, the order of events is the compliance. Non criminal checks come first. The offer is conditional, in the approved words. The criminal check comes only after the written offer. Salary history is never asked. And every candidate gets the same questions. Your recruiter runs the process. Your job is to never get ahead of it. To move through the module, use the arrows at the bottom of the screen, your keyboard arrows, or a swipe. Each page has one rule to read and one activity to complete. The narration reads each page as it turns. Tap Listen to hear a page again, or Auto to turn narration off. Progress, at the top right, counts each activity you finish. When all eight activities are done, you will see a completion message, your completion is recorded in Oracle Learning if you opened the module there, and the last page gives you a one page printable takeaway. When you are ready, turn the page. First, why the rules exist.',
  'why/1': 'First, why the rules exist. New York asks employers to judge people on the job, not on their past. Its fair chance rules mean criminal history is looked at only after a conditional offer, and only for what matters to the role. Its pay equity rules mean an offer is built from the job and the market, never from what someone earned before. And research on interviewing says the same thing the law does: the fairest process, the same questions for everyone with a scorecard, is also the one that predicts performance best. Try the three statements on this page.',
  'sequence/1': 'Now the sequence, which is the heart of this module. Phase one comes first: the non criminal checks, such as references and employment and education verification. No offer of any kind until your recruiter confirms phase one is complete. Then the conditional offer: verbal from you, using the approved words, and written from your recruiter. Only after the written conditional offer is issued does phase two begin, the criminal background check. If something comes back, Recruiting runs the fair chance process with the candidate. You never decide that alone. Put the six steps in order to lock it in.',
  'offer/1': 'The verbal offer has a script, and you say it the same way every time. We are excited to extend you a conditional offer, pending successful completion of background checks and final onboarding steps. Every word is doing a job. Conditional tells the candidate the offer can still change. Pending successful completion of background checks names what it depends on. Do not add that the job is theirs, that the check is a formality, or that they can give notice. Those sentences turn a conditional offer into a promise. Try the three ways of making the call and see which one holds.',
  'salary/1': 'Salary history. In New York you may not ask what a candidate earns now or earned before, directly, indirectly, or through a reference, and you may not use it to set an offer. You may ask what they expect, and you may share the range for the role, which is in the posting anyway. Offers come from the role, the market, and internal equity. If a candidate volunteers a number, let it pass: no follow up questions, and it does not go into the offer discussion. Sort the six lines on this page into ask or avoid.',
  'interview/1': 'A fair interview is a structured one. Before you meet anyone, agree with your recruiter on the four to six things the job really needs, one behavioral question for each, and what a strong answer sounds like. Ask every candidate the same questions in the same order. Score each answer against the rubric before you talk to the other interviewers, and write down what they said, not how they seemed. Then send your feedback to your recruiter within the agreed timeline, because slow processes lose good candidates. Some questions are never asked. Sort the six on this page.',
  'yourcall/1': 'Your call. Three situations hiring leaders in New York actually face: a candidate with a competing offer before phase one is done, a candidate who says their salary out loud, and a panel colleague scoring on something we never asked. Try all three responses in each one. The consequences teach more than the right answer.',
  'quiz/1': 'A quick check. Five questions on the sequence, the script, salary history, and the interview. Four of five completes the module, and each answer explains itself.',
  'next/1': 'Last page. Four hiring leader best practices, in order. One, timely feedback: send your interview feedback within the agreed timeline. Two, recruiter alignment: agree with your recruiter on the feedback and the decision. Three, phase one checks: confirm they are complete before any offer. Four, the conditional offer: use the required script. Below them are the handout, your recruiter, and the P C B help desk. When you have read them, mark this module done. Thank you for hiring the New York way.'
};
